USE Lobos_DB
GO

SELECT m.cp, M.municipio, P.PARTIDO, PR.PROVINCIA, PA.PAIS FROM Municipios AS M
FULL JOIN Partidos AS P 
ON M.IDPARTIDO=P.IDPARTIDO
FULL JOIN Provincias AS PR
ON P.IDPROVINCIA=PR.IdProvincia
FULL JOIN Paises AS PA
ON PR.IdPais=PA.IdPais
GO

SELECT * FROM ADMINISTRATIVOS
SELECT * FROM ESPECIALIDADES
SELECT * FROM ESPECIALIDADXPROF
SELECT * FROM EVOLUCIONES
SELECT * FROM HISTORIACLINICA
SELECT * FROM Municipios
SELECT * FROM PACIENTES
SELECT * FROM Paises
SELECT * FROM Partidos
SELECT * FROM Personas
SELECT * FROM PROFESIONALES
SELECT * FROM Provincias
SELECT * FROM RAZONESSOCIALES
SELECT * FROM TURNOS
GO


SELECT P.IDPERSONA AS ID, P.DNI, P.APELLIDO+', '+P.NOMBRE AS 'APELLIDO Y NOMBRE', CASE P.SEXO WHEN 1 THEN 'M' WHEN 0 THEN 'F' END AS SEXO, P.FechaNac AS 'FECHA NACIMIENTO', P.NACIONALIDAD, P.Calle, P.Numero, P.Piso, P.Depto, M.MUNICIPIO, P.TelCelular, P.TelFijo, P.FechaAlta, P.IdAdminAlta, P.FechaModif, P.IdAdminModif, P.FechaBaja, P. IdAdminBaja FROM Personas AS P LEFT JOIN Municipios AS M ON P.IDMUNICIPIO=M.IDMUNICIPIO LEFT JOIN Administrativos AS A ON P.IdPersona=A.IDPERSONA
GO











go
update Personas set IdPersona=3 where IdPersona=1


